name: Desktop Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  COVERAGE: true

jobs:
  desktop-smoke-test:
    name: Smoke Test
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Install Electron
        run: node ./node_modules/electron/install.js
        # pnpm might cache the electron binary
        continue-on-error: true
        env:
          ELECTRON_OVERRIDE_DIST_PATH: ./node_modules/.cache/electron
        working-directory: apps/desktop
      - name: Install Playwright's dependencies
        run: pnpm playwright install --with-deps chromium
        working-directory: apps/desktop
      - name: Build Packages
        run: pnpm run build:packages
      - name: Test
        run: pnpm test:smoke
        working-directory: apps/desktop
      - name: Collect coverage
        run: pnpm exec nyc report -t .nyc_output --report-dir coverage --reporter=json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: refine-desktop-smoke
          flags: apps
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
  desktop-e2e-test:
    name: E2E Test
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Install Electron
        run: node ./node_modules/electron/install.js
        # pnpm might cache the electron binary
        continue-on-error: true
        env:
          ELECTRON_OVERRIDE_DIST_PATH: ./node_modules/.cache/electron
        working-directory: apps/desktop
      - name: Install Playwright's dependencies
        run: pnpm playwright install --with-deps chromium
        working-directory: apps/desktop
      - name: Build Packages
        run: pnpm run build:packages
      - name: Test
        run: pnpm test:e2e
        working-directory: apps/desktop
      - name: Collect coverage
        run: pnpm exec nyc report -t .nyc_output --report-dir coverage --reporter=json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: refine-desktop
          flags: apps
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
