name: Storybook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  storybook:
    name: Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright's dependencies
        run: pnpm dlx playwright install --with-deps chromium
        working-directory: packages/core
      - name: Build Packages
        run: pnpm run build:packages
        working-directory: packages/core
      - name: Build Storybook
        run: pnpm run build-storybook --quiet
        working-directory: packages/core
      - name: Test
        run: |
          pnpm exec concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "pnpm exec serve storybook-static -l 6006 -s" \
          "pnpm exec wait-on tcp:6006 && pnpm test-storybook --coverage"
        working-directory: packages/core
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: core-storybook
          flags: packages
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          working-directory: ./packages/core
